<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/*
 * Trait EntityDefault
 *
 * This trait provides a standard implementation for entities in the system.
 * It defines a unique identifier(`id`) and a `title` for the entity, including
 * basic validations for the `title`. The trait can be used in any
 * entity that requires these features.
 *
 * Attributes:
 * - `id`: The unique identifier of the entity, automatically generated by the ORM.
 * - `title`: The title of the entity, which must be at least 3 characters long and cannot be blank.
 *
 * Methods:
 * - `getId()`: Returns the unique identifier of the entity.
 * - `getTitle()`: Returns the title of the entity.
 * - `setTitle(string $title)`: Sets the title of the entity.
 */


trait EntityDefault
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\NotBlank]
    #[Assert\Length(min: 3)]
    #[ORM\Column(length: 255)]
    private ?string $title = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }
}
